export const env = {
  TEST_EMAIL: import.meta.env.VITE_TEST_EMAIL,
  TEST_PASSWORD: import.meta.env.VITE_TEST_PASSWORD,
  BACKEND_URL: import.meta.env.VITE_BACKEND_URL,

  checkoutLinks: {
    BOLT_CHECKOUT_STARTER: import.meta.env.VITE_BOLT_CHECKOUT_STARTER,
    BOLT_CHECKOUT_BRONZE: import.meta.env.VITE_BOLT_CHECKOUT_BRONZE,
    BOLT_CHECKOUT_SILVER: import.meta.env.VITE_BOLT_CHECKOUT_SILVER,
    BOLT_CHECKOUT_GOLD: import.meta.env.VITE_BOLT_CHECKOUT_GOLD,
    BOLT_CHECKOUT_PLATINUM: import.meta.env.VITE_BOLT_CHECKOUT_PLATINUM,
    BOLT_CHECKOUT_DIAMOND: import.meta.env.VITE_BOLT_CHECKOUT_DIAMOND,
  }
}
